{{ 
  generate_navusoft_staging(
    entity_name='v_query_ar_history',
    unique_key='payload_hash',
    fields=[
{'name': 'date', 'type': 'timestamp_ntz'},
{'name': 'duedate', 'type': 'timestamp_ntz'},
{'name': 'account_division_id', 'type': 'number'},
{'name': 'account_id', 'type': 'number'},
{'name': 'site_division_id', 'type': 'number'},
{'name': 'batch_id', 'type': 'number'},
{'name': 'amount', 'type': 'number'},
{'name': 'appliedamount', 'type': 'number'},
{'name': 'balance', 'type': 'number'},
{'name': 'transfered_amount', 'type': 'number'},
{'name': 'refunded_amount', 'type': 'number'},
{'name': 'reversed_amount', 'type': 'number'},
{'name': 'site_id', 'type': 'number'},
{'name': 'id', 'type': 'varchar'},
{'name': 'type', 'type': 'varchar'},
{'name': 'period_id', 'type': 'varchar'},
{'name': 'referencenumber', 'type': 'varchar'},
{'name': 'account_division_name', 'type': 'varchar'},
{'name': 'accoount_name', 'type': 'varchar'},
{'name': 'account_address_line1', 'type': 'varchar'},
{'name': 'account_addressline2', 'type': 'varchar'},
{'name': 'account_city', 'type': 'varchar'},
{'name': 'account_state', 'type': 'varchar'},
{'name': 'account_zip', 'type': 'varchar'},
{'name': 'site_division_name', 'type': 'varchar'},
{'name': 'site_name', 'type': 'varchar'},
{'name': 'site_address_line1', 'type': 'varchar'},
{'name': 'site_addressline2', 'type': 'varchar'},
{'name': 'site_city', 'type': 'varchar'},
{'name': 'site_state', 'type': 'varchar'},
{'name': 'site_zip', 'type': 'varchar'},
{'name': 'billgroup_id', 'type': 'varchar'},
{'name': 'billing_group_name', 'type': 'varchar'},
{'name': 'payment_type', 'type': 'varchar'},
{'name': 'credit_card_type', 'type': 'varchar'},
{'name': 'note', 'type': 'varchar'},

    ]
  )
}}
