{{ config(
    materialized='incremental',
    tag='dims',
    unique_key='customer_activity_sk',
    incremental_strategy='merge',
    merge_update_columns=['is_current', 'valid_to']
) }}

{{ generate_dimension(
    source = "navusoft",
    table_name = "customer_activity",
    natural_key = ["account_id","record_id"],
    attributes = [
"site_id",
"account_name",
"account_division",
"account_divisionname",
"accountclass_name",
"account_addressline1",
"account_addressline2",
"account_city",
"account_state",
"account_zip_code",
"account_billing_phone",
"account_phone1",
"account_email",
"site_name",
"site_divisionname",
"site_addressline1",
"site_addressline2",
"site_city",
"site_state",
"site_zipcode",
"siteclass_name",
"billinggroup_name",
"service_region",
"taxregion_name",
"type",
"title",
"notes",
"assigned_to",
"created_by",
"status",
"completion_note",
"due_date",
"completed_date",
"appointment_datetime",
"creation_datetime",
    ],
    scd_type = 2
) }}