{{ 
  generate_navusoft_staging(
    entity_name='v_query_customeractivity',
    unique_key='payload_hash',
    fields=[
{'name': 'account_id', 'type': 'number'},
{'name': 'account_division', 'type': 'varchar'},
{'name': 'record_id', 'type': 'number'},
{'name': 'due_date', 'type': 'timestamp_ntz'},
{'name': 'completed_date', 'type': 'timestamp_ntz'},
{'name': 'appointment_datetime', 'type': 'timestamp_ntz'},
{'name': 'creation_datetime', 'type': 'timestamp_ntz'},
{'name': 'site_id', 'type': 'number'},
{'name': 'account_name', 'type': 'varchar'},
{'name': 'account_divisionname', 'type': 'varchar'},
{'name': 'account_addressline1', 'type': 'varchar'},
{'name': 'account_addressline2', 'type': 'varchar'},
{'name': 'account_city', 'type': 'varchar'},
{'name': 'account_state', 'type': 'varchar'},
{'name': 'account_zip_code', 'type': 'varchar'},
{'name': 'account_billing_phone', 'type': 'varchar'},
{'name': 'account_phone1', 'type': 'varchar'},
{'name': 'account_email', 'type': 'varchar'},
{'name': 'site_name', 'type': 'varchar'},
{'name': 'site_divisionname', 'type': 'varchar'},
{'name': 'site_addressline1', 'type': 'varchar'},
{'name': 'site_addressline2', 'type': 'varchar'},
{'name': 'site_city', 'type': 'varchar'},
{'name': 'site_state', 'type': 'varchar'},
{'name': 'site_zipcode', 'type': 'varchar'},
{'name': 'siteclass_name', 'type': 'varchar'},
{'name': 'billinggroup_name', 'type': 'varchar'},
{'name': 'accountclass_name', 'type': 'varchar'},
{'name': 'service_region', 'type': 'varchar'},
{'name': 'taxregion_name', 'type': 'varchar'},
{'name': 'type', 'type': 'varchar'},
{'name': 'title', 'type': 'varchar'},
{'name': 'notes', 'type': 'varchar'},
{'name': 'assigned_to', 'type': 'varchar'},
{'name': 'created_by', 'type': 'varchar'},
{'name': 'status', 'type': 'varchar'},
{'name': 'completion_note', 'type': 'varchar'},

    ]
  )
}}