{{ 
  generate_navusoft_staging(
    entity_name='v_query_revenue',
    unique_key='payload_hash',
    fields=[
{'name': 'date', 'type': 'timestamp_ntz'},
{'name': 'invoice_date', 'type': 'timestamp_ntz'},
{'name': 'startdate', 'type': 'timestamp_ntz'},
{'name': 'enddate', 'type': 'timestamp_ntz'},
{'name': 'type_value', 'type': 'number'},
{'name': 'emonth', 'type': 'number'},
{'name': 'bmonth', 'type': 'number'},
{'name': 'ar_id', 'type': 'number'},
{'name': 'division_id', 'type': 'number'},
{'name': 'account_id', 'type': 'number'},
{'name': 'workordernumber', 'type': 'number'},
{'name': 'servicerecord_id', 'type': 'number'},
{'name': 'invoice_id', 'type': 'number'},
{'name': 'billingbatch', 'type': 'number'},
{'name': 'account_class_id', 'type': 'number'},
{'name': 'prospectsource_id', 'type': 'number'},
{'name': 'salesrep_id', 'type': 'number'},
{'name': 'eyear', 'type': 'number'},
{'name': 'byear', 'type': 'number'},
{'name': 'surcharge_id', 'type': 'number'},
{'name': 'site_class_id', 'type': 'number'},
{'name': 'service_id', 'type': 'number'},
{'name': 'createdtimestamp', 'type': 'timestamp_ntz'},
{'name': 'quantity', 'type': 'number'},
{'name': 'grossquantity', 'type': 'number'},
{'name': 'label_chargeweight', 'type': 'number'},
{'name': 'amount', 'type': 'numeric(10,2)'},
{'name': 'site_id', 'type': 'number'},
{'name': 'type', 'type': 'varchar'},
{'name': 'code', 'type': 'varchar'},
{'name': 'description', 'type': 'varchar'},
{'name': 'lob_id', 'type': 'varchar'},
{'name': 'lob_name', 'type': 'varchar'},
{'name': 'account_name', 'type': 'varchar'},
{'name': 'account_name2', 'type': 'varchar'},
{'name': 'site_name', 'type': 'varchar'},
{'name': 'uom_name', 'type': 'varchar'},
{'name': 'volume', 'type': 'varchar'},
{'name': 'ar_period', 'type': 'varchar'},
{'name': 'earned_period', 'type': 'varchar'},
{'name': 'debitglaccount_id', 'type': 'varchar'},
{'name': 'creditglaccount_id', 'type': 'varchar'},
{'name': 'billgroup_id', 'type': 'varchar'},
{'name': 'serviceregion_id', 'type': 'varchar'},
{'name': 'serviceregion_name', 'type': 'varchar'},
{'name': 'billgroup_name', 'type': 'varchar'},
{'name': 'division_name', 'type': 'varchar'},
{'name': 'account_class_name', 'type': 'varchar'},
{'name': 'salesrep_name', 'type': 'varchar'},
{'name': 'materialtype_id', 'type': 'varchar'},
{'name': 'material_name', 'type': 'varchar'},
{'name': 'surchargename', 'type': 'varchar'},
{'name': 'chargecode_id', 'type': 'varchar'},
{'name': 'chargecode_name', 'type': 'varchar'},
{'name': 'servicecode_id', 'type': 'varchar'},
{'name': 'servicecode_name', 'type': 'varchar'},
{'name': 'is_temporary', 'type': 'varchar'},
{'name': 'manual_charge_note', 'type': 'varchar'},
{'name': 'site_class_name', 'type': 'varchar'},
{'name': 'ponumber', 'type': 'varchar'},

    ]
  )
}}