{{ 
  generate_navusoft_staging(
    entity_name='v_query_disposal_records',
    unique_key='payload_hash',
    fields=[
{'name': 'disposaldate', 'type': 'timestamp_ntz'},
{'name': 'division_id', 'type': 'number'},
{'name': 'disposallocation_id', 'type': 'number'},
{'name': 'materialclass_id', 'type': 'number'},
{'name': 'workordernumber', 'type': 'number'},
{'name': 'disposaluom_id', 'type': 'number'},
{'name': 'account_Id', 'type': 'number'},
{'name': 'tank_id', 'type': 'number'},
{'name': 'datetime', 'type': 'timestamp_ntz'},
{'name': 'start_timestamp', 'type': 'timestamp_ntz'},
{'name': 'end_timestamp', 'type': 'timestamp_ntz'},
{'name': 'quantity', 'type': 'number'},
{'name': 'calculated_quantity', 'type': 'number'},
{'name': 'minimum_quantity', 'type': 'number'},
{'name': 'disposalrate', 'type': 'number'},
{'name': 'fee1', 'type': 'number'},
{'name': 'fee2', 'type': 'number'},
{'name': 'fee3', 'type': 'number'},
{'name': 'fee4', 'type': 'number'},
{'name': 'fee5', 'type': 'number'},
{'name': 'totalcost', 'type': 'number'},
{'name': 'weight_in', 'type': 'number'},
{'name': 'weight_out', 'type': 'number'},
{'name': 'site_id', 'type': 'number'},
{'name': 'ticketID', 'type': 'varchar'},
{'name': 'period_id', 'type': 'varchar'},
{'name': 'division_name', 'type': 'varchar'},
{'name': 'disposallocation', 'type': 'varchar'},
{'name': 'route', 'type': 'varchar'},
{'name': 'truck_name', 'type': 'varchar'},
{'name': 'materialtype_id', 'type': 'varchar'},
{'name': 'material', 'type': 'varchar'},
{'name': 'driver', 'type': 'varchar'},
{'name': 'lob_id', 'type': 'varchar'},
{'name': 'uom', 'type': 'varchar'},
{'name': 'site_name', 'type': 'varchar'},
{'name': 'site_address_line_1', 'type': 'varchar'},
{'name': 'site_address_line_2', 'type': 'varchar'},
{'name': 'site_city', 'type': 'varchar'},
{'name': 'site_state', 'type': 'varchar'},
{'name': 'site_zip', 'type': 'varchar'},
{'name': 'serviceregion_id', 'type': 'number'},
{'name': 'service_region_name', 'type': 'varchar'},
{'name': 'tank_name', 'type': 'varchar'},
{'name': 'disposal_record_note', 'type': 'varchar'},
{'name': 'servicecode_name', 'type': 'varchar'},
{'name': 'workorder_po_number', 'type': 'number'},

    ]
  )
<<<<<<< HEAD
}}
=======
}}
>>>>>>> 4f71943348097e08bf897c819f49b561526606bd
