{{ config(
    materialized='incremental',
    tag='dims',
    unique_key='work_order_sk',
    incremental_strategy='merge',
    merge_update_columns=['is_current', 'valid_to']
) }}

{{ generate_dimension(
    source = "navusoft",
    table_name = "work_order",
    natural_key = ["workordernumber"],
    attributes = [
"site_id",
"division_id",
"account_id",
"route_id",
"route_default_disposallocation_id",
"truck_id",
"driver_id",
"posted_user_id",
"contact_id",
"lob_id",
"scheduled_date",
"posted_date",
"completion_date",
"createdtimestamp",
"quantity",
"disposal_quantity",
"sequence",
"minutes",
"optimizationtraveltime",
"optimizationdistance",
"equipment_volume",
"work_order_weight",
"wominimumchargeamount",
"workorder_revenue",
"revenue",
"surcharge_revenue",
"total_revenue",
"service_cost",
"disposal_cost",
"disposal_costs",
"total_cost",
"profit",
"status",
"posting_status",
    ],
    scd_type = 2
) }}