{{ config(
    materialized='incremental',
    tags=['dims'],
    unique_key='revenue_sk',
    incremental_strategy='merge',
    merge_update_columns=['is_current', 'valid_to']
) }}

{{ generate_dimension(
    source = "navusoft",
    table_name = "revenue",
    natural_key = ["ar_id"],
    attributes = [
"date",
"invoice_date",
"startdate",
"enddate",
"type_value",
"emonth",
"bmonth",
"division_id",
"account_id",
"workordernumber",
"servicerecord_id",
"invoice_id",
"billingbatch",
"account_class_id",
"prospectsource_id",
"salesrep_id",
"eyear",
"byear",
"surcharge_id",
"site_class_id",
"service_id",
"createdtimestamp",
"quantity",
"grossquantity",
"label_chargeweight",
"amount",
"site_id",
"type",
"code",
"description",
"lob_id",
"lob_name",
"account_name",
"account_name2",
"site_name",
"uom_name",
"volume",
"ar_period",
"earned_period",
"debitglaccount_id",
"creditglaccount_id",
"billgroup_id",
"serviceregion_id",
"serviceregion_name",
"billgroup_name",
"division_name",
"account_class_name",
"salesrep_name",
"materialtype_id",
"material_name",
"surchargename",
"chargecode_id",
"chargecode_name",
"servicecode_id",
"servicecode_name",
"is_temporary",
"manual_charge_note",
"site_class_name",
"ponumber",
    ],
    scd_type = 2
) }}