{{ config(
    materialized='incremental',
    tag='dims',
    unique_key='work_order_charges_sk',
    incremental_strategy='merge',
    merge_update_columns=['is_current', 'valid_to']
) }}

{{ generate_dimension(
    source = "navusoft",
    table_name = "work_order_charges",
    natural_key = ["servicerecordcharge_id"],
    attributes = [
"date",
"weightcharge",
"is_manifested",
"servicerecord_id",
"workordernumber",
"division_id",
"manifestconsolidationbatch_id",
"grossquantity",
"nochargequantity",
"perunitrate",
"quantity",
"weight",
"originalweight",
"volume",
"netvolume",
"netweight",
"mincharge",
"amount",
"site_id",
"worktype_id",
"division_name",
"serviceregion_id",
"serviceregion_name",
"site_name",
"chargecode_id",
"chargecode",
"dotdescription",
"materialtype_id",
"materialtype",
"equipmentype_id",
"equipmentype_name",
"unit",
"charge_abbreviation",
"equipmenttype_abbreviation",
"weight_oum",
"rate_uom",
"transfertext",
"epawastecode_abbreviation",
    ],
    scd_type = 2
) }}